# Generated by Django 4.2.3 on 2024-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("admin", "admin"), ("user", "user")],
                default="",
                max_length=20,
            ),
        ),
    ]
