# Generated by Django 4.2.3 on 2024-01-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="lead",
            name="hotel_address",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="lead",
            name="hotel_name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone_number",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="lead",
            name="url",
            field=models.CharField(default="", max_length=30),
        ),
    ]
