# Generated by Django 4.2.3 on 2024-01-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_lead_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
