# Generated by Django 4.2.3 on 2024-02-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_alter_lead_age_alter_lead_hotel_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
