# Generated by Django 4.2.3 on 2024-02-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_alter_lead_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="url",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
